matrix:
  include:
    - language: python
      python:
      - "3.8"
      - "3.9"
      install:
        - pip install -r requirements/common.txt
        - pip install coveralls
      script:
        - python back/manage.py test
        - coverage run --source=. back/manage.py test
      after_success:
        coveralls
      branches:
        only:
          - master

    - language: node_js
      node_js:
        - 14
      cache:
        directories:
          - node_modules
      before_install:
        - cd front
      install:
        - npm install
      script:
        - npm run lint
        - npm run build
