language: python
python:
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements/common.txt
  - pip install coveralls
script:
  - python back/manage.py test polls api
  - coverage run --source=. back/manage.py test
after_success:
  coveralls
branches:
  only:
    - master
